#!/usr/bin/env tsx
// Generates a human-readable catalog of every tool the WordBase MCP server exposes.
//
// How it works: instead of parsing tools.ts as text (brittle), it imports the real
// registerTools() and feeds it a mock server that records each tool() call. This is
// the same registration path the live MCP server uses, so the catalog can never drift
// from the actual tools — it IS the actual tools.
//
// The MCP tool handlers are never invoked here, so no database queries run. We still
// point WORDBASE_DB_PATH at an in-memory database because importing the service layer
// opens a connection at module-load time (packages/api/src/db/index.ts).
//
// Run: pnpm mcp:catalog   (from repo root)

process.env.WORDBASE_DB_PATH = ':memory:';
process.env.WORDBASE_API_KEY ??= 'catalog-generator-noop';

import { writeFileSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(__dirname, '..');

interface ToolParam {
  type?: string;
  description?: string;
  [k: string]: unknown;
}
interface Tool {
  name: string;
  description: string;
  params: Record<string, ToolParam>;
}

const tools: Tool[] = [];

// Arity-robust mock: name = first string, description = second string,
// schema = first plain-object arg after the strings. Tolerates registrations
// whose shape differs slightly so none are silently dropped.
const mockServer = {
  tool(...args: unknown[]) {
    const name = typeof args[0] === 'string' ? (args[0] as string) : '(unnamed)';
    const description = typeof args[1] === 'string' ? (args[1] as string) : '';
    const schema = args
      .slice(2)
      .find(
        (a) =>
          a !== null &&
          typeof a === 'object' &&
          !Array.isArray(a) &&
          typeof a !== 'function',
      ) as Record<string, ToolParam> | undefined;
    tools.push({ name, description, params: schema ?? {} });
  },
};

// Dynamic import AFTER env is set, so the in-memory DB path takes effect before
// db/index.ts opens its connection. (Static imports are hoisted and would run first.)
const { registerTools } = await import('../packages/api/src/mcp/tools.ts');
registerTools(mockServer as never);

if (tools.length === 0) {
  console.error('No tools registered — registration shape may have changed.');
  process.exit(1);
}

// Group by the prefix before the first underscore: blog / podcast / app / page.
const GROUP_TITLES: Record<string, string> = {
  blog: 'Blog',
  podcast: 'Podcast',
  app: 'Apps',
  page: 'Pages',
};
const GROUP_ORDER = ['blog', 'podcast', 'app', 'page'];

const groups = new Map<string, Tool[]>();
for (const t of tools) {
  const key = t.name.split('_')[0];
  if (!groups.has(key)) groups.set(key, []);
  groups.get(key)!.push(t);
}

const orderedKeys = [
  ...GROUP_ORDER.filter((k) => groups.has(k)),
  ...[...groups.keys()].filter((k) => !GROUP_ORDER.includes(k)).sort(),
];

const version = JSON.parse(
  readFileSync(join(repoRoot, 'packages/api/package.json'), 'utf8'),
).version as string;

const date = new Date().toISOString().split('T')[0];

let md = `# WordBase MCP — Tool Catalog\n\n`;
md += `> Auto-generated by \`pnpm mcp:catalog\` — do not edit by hand.\n`;
md += `> Source: \`packages/api/src/mcp/tools.ts\` · MCP server \`wordbase-blog\` v${version} · ${date}\n\n`;
md += `**${tools.length} tools** across ${orderedKeys.length} groups.\n\n`;

// Index
md += `## Index\n\n`;
for (const key of orderedKeys) {
  const title = GROUP_TITLES[key] ?? key;
  const names = groups
    .get(key)!
    .map((t) => `\`${t.name}\``)
    .join(' · ');
  md += `- **${title}** (${groups.get(key)!.length}): ${names}\n`;
}
md += `\n`;

// Detail
for (const key of orderedKeys) {
  const title = GROUP_TITLES[key] ?? key;
  const list = groups.get(key)!;
  md += `## ${title} (${list.length})\n\n`;
  for (const t of list) {
    md += `### \`${t.name}\`\n\n`;
    md += `${t.description || '_No description._'}\n\n`;
    const paramKeys = Object.keys(t.params);
    if (paramKeys.length === 0) {
      md += `_No parameters._\n\n`;
    } else {
      md += `| Parameter | Type | Description |\n`;
      md += `| --- | --- | --- |\n`;
      for (const pk of paramKeys) {
        const p = t.params[pk] ?? {};
        const type = p.type ?? '';
        const desc = (p.description ?? '').replace(/\|/g, '\\|');
        md += `| \`${pk}\` | ${type} | ${desc} |\n`;
      }
      md += `\n`;
    }
  }
}

const outPath = join(repoRoot, 'MCP-TOOLS.md');
writeFileSync(outPath, md);
console.log(`Wrote ${outPath} — ${tools.length} tools, ${orderedKeys.length} groups.`);
