#!/usr/bin/env tsx
// Generates a human-readable catalog of every tool the WordBase MCP server exposes.
//
// How it works: instead of parsing tools.ts as text (brittle), it imports the real
// registerTools() and feeds it a mock server that records each tool() call. This is
// the same registration path the live MCP server uses, so the catalog can never drift
// from the actual tools — it IS the actual tools.
//
// The MCP tool handlers are never invoked here, so no database queries run. We still
// point WORDBASE_DB_PATH at an in-memory database because importing the service layer
// opens a connection at module-load time (packages/api/src/db/index.ts).
//
// Run: pnpm mcp:catalog   (from repo root)

process.env.WORDBASE_DB_PATH = ':memory:';
process.env.WORDBASE_API_KEY ??= 'catalog-generator-noop';

import { writeFileSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(__dirname, '..');

interface ToolParam {
  type?: string;
  description?: string;
  [k: string]: unknown;
}
interface Tool {
  name: string;
  description: string;
  title?: string;
  annotations?: Record<string, unknown>;
  params: Record<string, ToolParam>;
}

const tools: Tool[] = [];

// Arity-robust mock: name = first string, description = second string. We no
// longer read the schema arg here — once compiled to Zod it can't be walked
// back into a { type, description } descriptor without silently degrading the
// rendered Type column, so the descriptor is pulled from REGISTERED_DESCRIPTORS
// after registerTools() returns (that Map is populated by the shim itself as a
// side effect of registration, so it can't drift from the actual tools).
// registerTool(name, config, _handler) mirrors the real McpServer's SDK-1.27
// entry point so the shim takes the same branch it takes in production.
const mockServer = {
  tool(...args: unknown[]) {
    const name = typeof args[0] === 'string' ? (args[0] as string) : '(unnamed)';
    const description = typeof args[1] === 'string' ? (args[1] as string) : '';
    tools.push({ name, description, params: {} });
  },
  registerTool(
    name: string,
    config: { title?: string; description?: string; annotations?: Record<string, unknown> },
    _handler: unknown,
  ) {
    tools.push({
      name,
      description: config.description ?? '',
      title: config.title,
      annotations: config.annotations,
      params: {},
    });
  },
};

// Dynamic import AFTER env is set, so the in-memory DB path takes effect before
// db/index.ts opens its connection. (Static imports are hoisted and would run first.)
const { registerTools, REGISTERED_DESCRIPTORS } = await import('../packages/api/src/mcp/tools.ts');
registerTools(mockServer as never);

for (const t of tools) {
  const descriptor = REGISTERED_DESCRIPTORS.get(t.name);
  if (descriptor) t.params = descriptor as Record<string, ToolParam>;
}

if (tools.length === 0) {
  console.error('No tools registered — registration shape may have changed.');
  process.exit(1);
}

// Group by the prefix before the first underscore.
const GROUP_TITLES: Record<string, string> = {
  post: 'Posts',
  tag: 'Tags',
  category: 'Categories',
  media: 'Media',
  comment: 'Comments',
  analytics: 'Analytics',
  build: 'Build',
  redirect: 'Redirects',
  podcast: 'Podcast',
  app: 'Apps',
  page: 'Pages',
  settings: 'Settings',
  observability: 'Observability',
  i18n: 'i18n',
};
const GROUP_ORDER = [
  'post',
  'tag',
  'category',
  'media',
  'comment',
  'analytics',
  'build',
  'redirect',
  'podcast',
  'app',
  'page',
  'settings',
  'observability',
  'i18n',
];

const groups = new Map<string, Tool[]>();
for (const t of tools) {
  const key = t.name.split('_')[0];
  if (!groups.has(key)) groups.set(key, []);
  groups.get(key)!.push(t);
}

const orderedKeys = [
  ...GROUP_ORDER.filter((k) => groups.has(k)),
  ...[...groups.keys()].filter((k) => !GROUP_ORDER.includes(k)).sort(),
];

const version = JSON.parse(
  readFileSync(join(repoRoot, 'packages/api/package.json'), 'utf8'),
).version as string;

const date = new Date().toISOString().split('T')[0];

let md = `# WordBase MCP — Tool Catalog\n\n`;
md += `> Auto-generated by \`pnpm mcp:catalog\` — do not edit by hand.\n`;
md += `> Source: \`packages/api/src/mcp/tools.ts\` · MCP server \`wordbase-blog\` v${version} · ${date}\n\n`;
md += `**${tools.length} tools** across ${orderedKeys.length} groups.\n\n`;

// Index
md += `## Index\n\n`;
for (const key of orderedKeys) {
  const title = GROUP_TITLES[key] ?? key;
  const names = groups
    .get(key)!
    .map((t) => `\`${t.name}\``)
    .join(' · ');
  md += `- **${title}** (${groups.get(key)!.length}): ${names}\n`;
}
md += `\n`;

// Detail
for (const key of orderedKeys) {
  const title = GROUP_TITLES[key] ?? key;
  const list = groups.get(key)!;
  md += `## ${title} (${list.length})\n\n`;
  for (const t of list) {
    md += `### \`${t.name}\`${t.title ? ` — ${t.title}` : ''}\n\n`;
    md += `${t.description || '_No description._'}\n\n`;
    if (t.annotations && Object.keys(t.annotations).length > 0) {
      const flags = Object.entries(t.annotations)
        .map(([k, v]) => `\`${k}: ${v}\``)
        .join(' · ');
      md += `_Annotations:_ ${flags}\n\n`;
    }
    const paramKeys = Object.keys(t.params);
    if (paramKeys.length === 0) {
      md += `_No parameters._\n\n`;
    } else {
      md += `| Parameter | Type | Description |\n`;
      md += `| --- | --- | --- |\n`;
      for (const pk of paramKeys) {
        const p = t.params[pk] ?? {};
        const type = p.type ?? '';
        const desc = (p.description ?? '').replace(/\|/g, '\\|');
        md += `| \`${pk}\` | ${type} | ${desc} |\n`;
      }
      md += `\n`;
    }
  }
}

const outPath = join(repoRoot, 'MCP-TOOLS.md');
writeFileSync(outPath, md);
console.log(`Wrote ${outPath} — ${tools.length} tools, ${orderedKeys.length} groups.`);
